[2025-02-10T20:12:41.939+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-10T20:12:41.959+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: web_to_snowflake.load_to_snowflake manual__2025-02-10T20:12:19.177997+00:00 [queued]>
[2025-02-10T20:12:41.969+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: web_to_snowflake.load_to_snowflake manual__2025-02-10T20:12:19.177997+00:00 [queued]>
[2025-02-10T20:12:41.971+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-02-10T20:12:41.988+0000] {taskinstance.py:2889} INFO - Executing <Task(SnowflakeOperator): load_to_snowflake> on 2025-02-10 20:12:19.177997+00:00
[2025-02-10T20:12:42.002+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5828) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-10T20:12:42.005+0000] {standard_task_runner.py:72} INFO - Started process 5830 to run task
[2025-02-10T20:12:42.005+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'web_to_snowflake', 'load_to_snowflake', 'manual__2025-02-10T20:12:19.177997+00:00', '--job-id', '60', '--raw', '--subdir', 'DAGS_FOLDER/web_to_snowflake.py', '--cfg-path', '/tmp/tmpmhwlx07v']
[2025-02-10T20:12:42.008+0000] {standard_task_runner.py:105} INFO - Job 60: Subtask load_to_snowflake
[2025-02-10T20:12:42.073+0000] {task_command.py:467} INFO - Running <TaskInstance: web_to_snowflake.load_to_snowflake manual__2025-02-10T20:12:19.177997+00:00 [running]> on host 0370ed89eba8
[2025-02-10T20:12:42.170+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='web_to_snowflake' AIRFLOW_CTX_TASK_ID='load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-02-10T20:12:19.177997+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-10T20:12:19.177997+00:00'
[2025-02-10T20:12:42.172+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-10T20:12:42.188+0000] {sql.py:278} INFO - Executing: 
    COPY INTO weather_table(temperature, humidity, date, temperature_celsius)
    FROM @my_s3_stage/2025-02-10
    FILE_FORMAT = my_csv_format
    ON_ERROR = 'CONTINUE';
    
[2025-02-10T20:12:42.205+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-02-10T20:12:42.219+0000] {base.py:84} INFO - Retrieving connection 'snowflake_default'
[2025-02-10T20:12:42.221+0000] {connection.py:414} INFO - Snowflake Connector for Python Version: 3.12.4, Python Version: 3.12.8, Platform: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-02-10T20:12:42.223+0000] {connection.py:1197} INFO - Connecting to GLOBAL Snowflake domain
[2025-02-10T20:12:42.224+0000] {connection.py:1278} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-02-10T20:12:42.960+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-10T20:12:42.962+0000] {sql.py:553} INFO - Running statement: COPY INTO weather_table(temperature, humidity, date, temperature_celsius)
    FROM @my_s3_stage/2025-02-10
    FILE_FORMAT = my_csv_format
    ON_ERROR = 'CONTINUE';, parameters: None
[2025-02-10T20:12:44.326+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-10T20:12:44.328+0000] {sql.py:562} INFO - Rows affected: 1
[2025-02-10T20:12:44.330+0000] {snowflake.py:447} INFO - Rows affected: 1
[2025-02-10T20:12:44.331+0000] {snowflake.py:448} INFO - Snowflake query id: 01ba4e5c-3202-c1cb-0005-f712000220da
[2025-02-10T20:12:44.614+0000] {cursor.py:1166} INFO - Number of results in first chunk: 1
[2025-02-10T20:12:44.616+0000] {connection.py:789} INFO - closed
[2025-02-10T20:12:44.674+0000] {connection.py:795} INFO - No async queries seem to be running, deleting session
[2025-02-10T20:12:44.783+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-10T20:12:44.785+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=web_to_snowflake, task_id=load_to_snowflake, run_id=manual__2025-02-10T20:12:19.177997+00:00, execution_date=20250210T201219, start_date=20250210T201241, end_date=20250210T201244
[2025-02-10T20:12:44.846+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-02-10T20:12:44.869+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-10T20:12:44.874+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
